- hwloc/topology-cuda.c
To support getting the number of cores on CUDA hardware capable of compute capability 5.x the corresponding switch statement has to be etended.
See: http://docs.nvidia.com/cuda/cuda-c-programming-guide/#architecture-5-x
> Add support for CUDA compute capability 5.x

- config/hwloc.m4
This makes a difference when configuring in embedded mode.
Note that this was already fixed on master; perhaps it mistakenly didn't come over to v1.10/v1.11?
(cherry picked from commit open-mpi/hwloc@242356d8d480e0808834717d95b57c1d35b13fbd)
> v1.11: hwloc.m4: use $HWLOC_TOP_srcdir, not $srcdir

- config/hwloc.m4
This makes a difference when configuring in embedded mode.
Note that this fix is already on master; looks like it simply may not have come to v1.10/v1.11...?
> v1.10: hwloc.m4: use $HWLOC_TOP_srcdir, not $srcdir

- hwloc/bind.c
clang on OS X warns that p may be uninitialized.  Best I can figure, it's assuming posix_memalign() may fail to fill &p and still return an errno of 0.  Technically -- on a buggy system -- that can happen.  So we might as well initialize p to be NULL just to cover all cases / be defensive.
@bgoglin Got any objections to this minor warning squash?
> bind.c: fix silly compiler warning

- NEWS
- config/hwloc.m4
- config/hwloc_internal.m4
- configure.ac
- contrib/windows/private_config.h
- doc/hwloc.doxy
- hwloc/topology-linux.c
@jsquyres This came up during the OMPI dev meeting when discussing with @markalle. Platform-MPI currently dlopens libnuma.so instead of keeping the hardwired dependency in libhwloc.so. I figured we could try to just remove the libnuma dependency entirely. It's easy, except when redefining the missing syscalls. I still need to check whether syscall() is well supported with 6 parameters on reasonably old distros running on NUMA machines.
Likely for hwloc v2.0 only, except if somebody is sure this can safely go to v1.11.3.
> RFC: Remove libnuma dependency

- doc/Makefile.am
If you try to run "make dist" when you don't have all the right
documentation generation tools, you currently get a misleading error
about a file being missing.  This commit adds a helpful message
specifically telling you that you are missing some tools that hwloc
needs, and therefore "make dist" will fail.
> docs: print helpful error when "make dist" should fail

- config/hwloc.m4
Ensure that HAVE_DECL_RUNNING_ON_VALGRIND is always defined, even when
we're in embedded mode.  Fixes #197.
@bgoglin Have a look
> hwloc.m4: fix compiler warning in embedded mode

- contrib/nightly/make_snapshot_tarball
Nightly snapshots will now be named:
hwloc-${BRANCHNAME}-${YYYYMMDDHHMM}-${SHORTHASH}.tar.${COMPRESSION}.
Essentially cherry-picked from Open MPI:
* open-mpi/ompi@78d1e4ebff45fe0c3ca291cdf37de145510062d9
* open-mpi/ompi@a47ad865d320a91f633378da744f7c60affc45dd
> make_snapshot_tarball: update nightly filename

- contrib/nightly/make_snapshot_tarball
Nightly snapshots will now be named:
hwloc-${BRANCHNAME}-${YYYYMMDDHHMM}-${SHORTHASH}.tar.${COMPRESSION}.
Essentially cherry-picked from Open MPI:
* open-mpi/ompi@78d1e4ebff45fe0c3ca291cdf37de145510062d9
* open-mpi/ompi@a47ad865d320a91f633378da744f7c60affc45dd
(cherry picked from commit db9eb54a9cdc32b643f2c9f2d56d98271765d157)
> v1.11: make_snapshot_tarball: update nightly filename

- NEWS
- hwloc/distances.c
- hwloc/topology-cuda.c
- hwloc/topology-nvml.c
- hwloc/topology-opencl.c
- hwloc/topology-synthetic.c
- hwloc/topology-xml.c
- hwloc/topology.c
- hwloc/traversal.c
- include/hwloc.h
- include/hwloc/diff.h
- include/hwloc/distances.h
- include/hwloc/helper.h
- include/hwloc/inlines.h
- tests/hwloc/glibc-sched.c
- tests/hwloc/hwloc_bitmap_string.c
- tests/hwloc/hwloc_distances.c
- tests/hwloc/hwloc_get_closest_objs.c
- tests/hwloc/hwloc_groups.c
- tests/hwloc/hwloc_object_userdata.c
- tests/hwloc/hwloc_topology_diff.c
- tests/hwloc/hwloc_topology_restrict.c
- utils/hwloc/hwloc-annotate.c
- utils/hwloc/hwloc-bind.c
- utils/hwloc/hwloc-calc.c
- utils/hwloc/hwloc-calc.h
- utils/hwloc/hwloc-info.c
- utils/hwloc/misc.h
- utils/lstopo/lstopo-draw.c
- utils/lstopo/lstopo-text.c
Change obj->depth to signed int, and all relevant function manipulating
object depths.
We have negative depth for special levels so we cast in lots of places.
This is becoming even more common with the NUMAnode special level.
Also change hwloc_topology_get_depth() to signed to avoid signedness
comparison warnings when iterating over depths.
That one is less obvious since it's always >0 and even an unsigned internally.
Cache/Bridge/Group specific depth attr are still unsigned,
those are never negative.
It's not clear whether mixing signed depth for object and unsigned
for attribute could cause confusion.
Signed-off-by: Brice Goglin <Brice.Goglin@inria.fr>
> API: change level depth to signed int

- NEWS
- doc/Makefile.am
- doc/examples/nodeset+membind+policy.c
- hwloc/diff.c
- hwloc/topology-aix.c
- hwloc/topology-bgq.c
- hwloc/topology-darwin.c
- hwloc/topology-freebsd.c
- hwloc/topology-linux.c
- hwloc/topology-netbsd.c
- hwloc/topology-solaris.c
- hwloc/topology-synthetic.c
- hwloc/topology-windows.c
- hwloc/topology-xml.c
- hwloc/topology.c
- hwloc/traversal.c
- include/hwloc.h
- include/hwloc/linux-libnuma.h
- include/hwloc/rename.h
- include/private/private.h
- tests/hwloc/hwloc_get_area_memlocation.c
- tests/hwloc/hwloc_topology_diff.c
- tests/hwloc/hwloc_topology_restrict.c
- tests/hwloc/linux-libnuma.c
- utils/hwloc/hwloc-info.c
- utils/lstopo/lstopo-draw.c
- utils/lstopo/lstopo-text.c
Only NUMA nodes have memory, so it makes sense to change obj->memory into obj->attr->numanode
However obj->memory.total_memory is used for all objects (especially root), so that one becomes obj->total_memory.
> Move local_memory to NUMA node specific attrs

- NEWS
- doc/Makefile.am
- doc/hwloc.doxy
- hwloc/hwloc2.dtd
- hwloc/topology-synthetic.c
- hwloc/topology-xml.c
- hwloc/topology.c
- hwloc/traversal.c
- include/hwloc.h
- include/hwloc/deprecated.h
- include/hwloc/inlines.h
- include/hwloc/rename.h
- tests/hwloc/hwloc_backends.c
- tests/hwloc/hwloc_get_obj_inside_cpuset.c
- tests/hwloc/hwloc_groups.c
- tests/hwloc/hwloc_type_depth.c
- utils/hwloc/hwloc.7in
- utils/lstopo/lstopo-draw.c
- utils/lstopo/lstopo.h
- utils/lstopo/test-lstopo.sh.in
We don't support topologies made of multiple machines anymore (kerrighed is dead, we removed its support, and custom assembly of topologies has been removed too). Therefore, the only way to get a topology with a System object above Machine is synthetic.
I don't think we will ever again support a single topology made of different/independent operating system instances, at least because binding isn't possible there. But we still support assembly of multiple machines managed by a single OS (SGI NumaLink, ScaleMP vSMP, etc). So maybe Machine isn't the right name, but I am not sure it's worth changing it.
Anyway, once we remove System, we can now clarify that root is always Machine. This means the "network drawing" code isn't needed in lstopo anymore.
> Remove the "System" object type

- utils/hwloc/hwloc-dump-hwdata-knl.c
We always matched because the last iteration would strncmp() with
len=0.
Signed-off-by: Grzegorz Andrejczuk <grzegorz.andrejczuk@intel.com>
> hwloc-dump-hwdata: fix the lookup for KNL SMBIOS entries

- hwloc/misc.c
- hwloc/topology-linux.c
- hwloc/topology-pci.c
- hwloc/topology-xml.c
- utils/hwloc/hwloc-bind.c
Fix 2 kinds of compiler warnings:
1. Uninitialized variables
1. Local symbols shadowing global symbols
> Miscellaneous compiler warning fixes

- VERSION
- config/hwloc.m4
- config/hwloc_get_version.sh
- contrib/windows/hwloc_config.h
- contrib/windows/private_config.h
- doc/hwloc.doxy
- include/hwloc.h
- include/hwloc/autogen/config.h.in
- tests/hwloc/linux/allowed/test-topology.sh.in
- tests/hwloc/linux/test-topology.sh.in
- tests/hwloc/x86/test-topology.sh.in
- utils/hwloc/test-hwloc-info.sh.in
- utils/lstopo/test-lstopo.sh.in
OMPI would like a way to check the hwloc library version (not API version) from external configure scripts (open-mpi/ompi#5395). We currently have HWLOC_VERSION defined in private/autogen/config.h
It's only there because it wasn't prefixed with HWLOC_ in the past. Now that it's properly prefixed, there's no reason to keep it private.
Also add HWLOC_VERSION_{MAJOR,MINOR,RELEASE,GREEK} to avoid external parsing.
> Define HWLOC_VERSION* in hwloc/autogen/config.h public header

- include/hwloc.h
The documentation used a right-shift operator to construct HWLOC_API_VERSION from a release version. This made no sense and the left-shift operator should be used.
Signed-off-by: Hannes Weisbach hannes.weisbach@gmail.com
> Fix documentation on API version

- utils/hwloc/common-ps.c
* Remove unused variable
* Change string by format to comply with -Wformat-security
> Silence warnings when compiled on macOS Sierra 10.12.6

- hwloc/topology.c
- include/private/private.h
Signed-off-by: Samuel Thibault <samuel.thibault@ens-lyon.org>
> bsd: Make hwloc_get_sysctl able to return 64bit values

- config/hwloc.m4
- configure.ac
- contrib/dist/publish_doc
Long story short - I'm using **hwloc** on a system, on which I lose executable permissions, and since I have no control over this, I came to this solution, which, I thought, might be beneficial to someone else using **hwloc**.
> Execute hwloc_get_version.sh with sh

- contrib/completion/hwloc-completion.bash
Currently the bash completion script breaks for zsh since `test ${BASH_VERSINFO[0]} -lt 4 && return` gives the error `/etc/bash_completion.d/hwloc-completion.bash:test:7: unknown condition: -lt` because `BASH_VERSINFO` is empty.
I'm not a shell wizard, so my fix is probably not idiomatic. I did make sure it works on Bash 3, 4, 5 and zsh.
> Fix bash completion for zsh

- NEWS
- contrib/windows/lstopo-no-graphics.vcxproj
- contrib/windows/lstopo-no-graphics.vcxproj.filters
- contrib/windows/lstopo-win.vcxproj
- contrib/windows/lstopo-win.vcxproj.filters
- contrib/windows/lstopo.vcxproj
- contrib/windows/lstopo.vcxproj.filters
- doc/hwloc.doxy
- utils/lstopo/Makefile.am
- utils/lstopo/lstopo-no-graphics.1in
- utils/lstopo/lstopo-tikz.c
- utils/lstopo/lstopo.c
- utils/lstopo/lstopo.h
- utils/lstopo/test-lstopo.sh.in
I wanted a proper output for inclusion into a LaTeX document and from how straight forward it was to change from a SVG to a tikz picture, I thought it would be useful to have it directly available.
However, I have two issues:
- How can I enable the colors? I tried to define the `declare_color` function, but it seems to never be called.
- Where can I add a flag that insert a backslash in front of the _sharp_ character to have it escaped for tikz?
The result file creates a standalone tex file which can be compiled and depends on `tikz` and `xcolor`. The file can be also be easily included into a latex project.
> Lstopo tikz

- contrib/ci.inria.fr/job-0-tarball.sh
PR to test the script that handles PR in the CI.
Signed-off-by: Brice Goglin <Brice.Goglin@inria.fr>
> contrib/ci.inria.fr: support PR URLs with slashes as branch names

- contrib/completion/hwloc-completion.bash
The PR from July 23, was lacking the update of the auto-completion of the output format. This commit fixes it. As the man page states both tikz and tex, should `tex` be added as well?
> lstopo/tikz: Update auto-completion with tikz output format

- config/hwloc_internal.m4
On my system hwloc never detects ncurses, because `tparm` lives in `libtinfo.so`
> Look for tinfo too

- NEWS
- doc/hwloc.doxy
- utils/lstopo/Makefile.am
- utils/lstopo/lstopo-no-graphics.1in
- utils/lstopo/lstopo-tikz.c
- utils/lstopo/lstopo.c
- utils/lstopo/lstopo.h
- utils/lstopo/test-lstopo.sh.in
The previous HPE copyrights were not complying with the company's policy format. This PR fixes the issue.
> Update HPE copyrights

- utils/hwloc/hwloc-bind.1in
- utils/hwloc/hwloc-calc.1in
Add some examples using the "-H" option to hwloc-calc to hwloc-bind(1)
and hwloc-calc(1).
> docs: add "hwloc-calc -H" examples

- config/hwloc_check_vendor.m4
* PGI compiler has a GNU compatability mode so `__GNUC__` is defined by
`pgcc`. So first check for `__PGI` before checking for GNU.
> Move PGI compiler check before GNU

- hwloc/topology-linux.c
Running hwloc-ls with valgrind shows two memory leak when bailling out.
```
==21928== 64 bytes in 1 blocks are definitely lost in loss record 1 of 2
==21928==    at 0x4835753: malloc (vg_replace_malloc.c:309)
==21928==    by 0x4895E45: hwloc_linux_cpufreqs_init (topology-linux.c:4078)
==21928==    by 0x4895E45: look_sysfscpu (topology-linux.c:4236)
==21928==    by 0x4899584: hwloc_linuxfs_look_cpu (topology-linux.c:5309)
==21928==    by 0x4899584: hwloc_look_linuxfs (topology-linux.c:6538)
==21928==    by 0x4865DED: hwloc_discover_by_phase.isra.0 (topology.c:3229)
==21928==    by 0x486DE06: hwloc_discover (topology.c:3309)
==21928==    by 0x486DE06: hwloc_topology_load (topology.c:3958)
==21928==    by 0x40510A: main (lstopo.c:1484)
==21928== 
==21928== 64 bytes in 1 blocks are definitely …
```
> Fixed a memory leak when destroying hwloc_linux_cpufreqs objects.

- NEWS
- config/hwloc.m4
- config/hwloc_internal.m4
- doc/hwloc.doxy
- hwloc/Makefile.am
Specifies where CUDA is installed to avoid having to pass
C_INCLUDE_PATH and LIBRARY_PATH at build time.
LD_LIBRARY_PATH is still required at runtime.
The CUDA directory is also used for looking for OpenCL and NVML
subcomponents.
Thanks to Andrea Bocci for the suggestion.
Refs #392.
Signed-off-by: Brice Goglin <Brice.Goglin@inria.fr>
> configure: add --with-cuda=<dir>

- config/hwloc.m4
* The PGI compiler is identified as a GCC compiler (so `$GCC == yes`)
This can cause problems if the user accidentally adds `--enable-picky`
or if the `$GCC` variable is used to check if it is safe to add GCC
specific compiler flags.
* Instead of using `$GCC` we can use the vendor string returned by
`_HWLOC_C_COMPILER_VENDOR`.
> Fix GCC checks to use the vendor name

- config/hwloc_check_vendor.m4
- By default newer xlc compilers only define __ibmxl__ now.
https://www.ibm.com/support/knowledgecenter/en/SSXVZZ_13.1.6/com.ibm.xlcpp1316.lelinux.doc/compiler_ref/xlmacros.html
- Most compilers define the __GNU__ macro, so put it at the bottom
as a catch-all.
Tested with gcc, xlc, pgi and clang.
> Fix xl compiler check

- config/hwloc_internal.m4
On macOS there seems to be a symlink from /usr/lib/libtermcap.dylib to
libncurses.5.4.dylib, which is the first option hwloc currently
considers for detecting ncurses. If you install ncurses with brew or
spack, you don't get this symlink, so hwloc will always link to the
system ncurses instead of the brew/spack version.
By considering libncurses first this should be fixed.
> Make -ltermcap the last option for ncurses

- NEWS
- doc/Makefile.am
- doc/hwloc.doxy
- hwloc/distances.c
- hwloc/topology-xml.c
- include/hwloc/deprecated.h
- include/hwloc/distances.h
- include/hwloc/plugins.h
- include/hwloc/rename.h
- include/private/private.h
- tests/hwloc/hwloc_distances.c
- tests/hwloc/hwloc_groups.c
- tests/hwloc/hwloc_topology_dup.c
- tests/hwloc/hwloc_topology_restrict.c
- tests/hwloc/shmem.c
- utils/hwloc/hwloc-annotate.c
hwlc_distances_add() is split into add_create()+add_values()+add_commit() to allow specifying a name argument without having yet another function with too many arguments. Splitting will also let us add intermediate calls if we ever need to add more parameters.
The main end-user API in hwloc/distances is deprecated in favor of this new API. And a plugin-specific one is added because GPU backends will need it (only non-plugin backends could add distances before).
> New API for adding distances

- NEWS
- doc/hwloc.doxy
- hwloc/topology-rsmi.c
- include/hwloc/distances.h
@miketxli Here's a totally untested draft of XGMI distance matrix. I just put 100 in the matrix when your code found a XGMI peer (you said InfinityFabric links are 100GB/s, right). The code isn't ready to merge (I'd need to export the distances_add() function to plugins, right now it will only work when the RSMI backend is not a separate plugin), but I'd like you to test/fix/discuss the code in the meantime. I am working on NVLink and oneAPI support at the same time.
If you run lstopo -v, you should get a distance matrix between OSDev at the bottom of the output. The numbers on the first row and first column are the OS Devices logical indexes (those you see as L#1 in lstopo --only osdev -v | grep rsmi).
The diagonal would keep 0 which is a normal because because there's no XGMI link to …
> XGMIBandwidth matrix

- utils/hwloc/hwloc-calc.h
The cores are being counted from 0 so `core:2-3` should correspond to the third and fourth cores. Also, `core` is missing the plural 's'.
> utils/hwloc-calc: Fix erroneous index in help message

- NEWS
- config/hwloc.m4
- doc/hwloc.doxy
- hwloc/Makefile.am
- hwloc/topology-darwin.c
- include/hwloc/cpukinds.h
- tests/hwloc/ports/Makefile.am
- tests/hwloc/ports/include/darwin/CoreFoundation/CoreFoundation.h
- tests/hwloc/ports/include/darwin/IOKit/IOKitLib.h
```
$ lstopo --cpukinds
CPU kind #0 efficiency 0 cpuset 0x0000000f
DarwinCompatible = apple,icestorm;ARM,v8
CPU kind #1 efficiency 1 cpuset 0x000000f0
DarwinCompatible = apple,firestorm;ARM,v8
$ utils/hwloc/hwloc-calc --cpukind 1 -N core all
4
```
> Detect cpukinds on Mac OS X for Apple M1 hybrid CPU support

- NEWS
- hwloc/topology-linux.c
MPOL_PREFERRED is less strict than MPOL_BIND since it falls back
to other node if the given one is full. But it works only with
a single node. Other (non-first physical index) are just ignored.
MPOL_PREFERRED_MANY in 5.15 fixes this.
Use MPOL_PREFERRED_MANY by default for membind. If it fails,
try MPOL_PREFERRED. If it works, assume MPOL_PREFERRED_MANY isn't
supported in the current kernel.
Closes #236
Signed-off-by: Brice Goglin <Brice.Goglin@inria.fr>
> linux: use MPOL_PREFERRED_MANY when available

- NEWS
- hwloc/topology-windows.c
- include/Makefile.am
- include/private/windows.h
- tests/hwloc/ports/include/windows/windows.h
- utils/lstopo/lstopo-windows.c
Recent windows 10 builds (and windows 11) can expose the locality of NUMA nodes and caches across multiple processor groups. Support is backward compatible, no need to wait for all users to upgrade to those recent windows releases.
There's still an issue about processor groups spanning across multiple sockets/NUMAs #497 but it's not clear if that's a Windows bug (all this Windows changes are fairly recent and documentation is not finalized yet) or if that's expected.
> Support for NUMA nodes and caches spanning multiple Windows processor groups

- NEWS
- contrib/completion/bash/hwloc
- utils/lstopo/lstopo-android.c
- utils/lstopo/lstopo-ascii.c
- utils/lstopo/lstopo-cairo.c
- utils/lstopo/lstopo-draw.c
- utils/lstopo/lstopo-fig.c
- utils/lstopo/lstopo-no-graphics.1in
- utils/lstopo/lstopo-svg.c
- utils/lstopo/lstopo-tikz.c
- utils/lstopo/lstopo-windows.c
- utils/lstopo/lstopo.c
- utils/lstopo/lstopo.h
Define "palette" structures instead of hardwiring lots of color structures.
Cleanup the actual list of colors.
Add "--grey" to switch lstopo to greyscale output.
Add "--palette white" to disable all color backgrounds.
Add "--palette core=#ff00ff" to change the color of "Core" boxes.
Adding a colorblind palette will be easy.
> lstopo: improve color management and add grey and white palettes

- autogen.sh
Currently, if autoreconf is missing on the building system, the autogen.sh script will continue, in a buggy way:
```
$ ./autogen.sh 
./autogen.sh: line 9: autoreconf: command not found
Checking whether configure needs patching for MacOS Big Sur libtool.m4 bug... grep: configure: No such file or directory
grep: configure: No such file or directory
yes
Trying to patch configure...
can't find file to patch at input line 9
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|Updated from libtool.m4 patch:
|
|[PATCH] Improve macOS version detection to support macOS 11 and simplify legacy logic
|
|Signed-off-by: Jeremy Huddleston Sequoia <jeremyhu@apple.com>
|
|--- hwloc/configure.old	2020-11-25 16:03:04.225097149 +0100
|+++ …
```
> autogen: exit on first error

- config/hwloc.m4
- configure.ac
* The Nvidia ML library is provided by a stub which can fool
the linker into thinking that the actual library is on the system
even when it is not. This can cause a runtime failure on such
systems.
- Strengthen the `nvidia-ml` library check by adding a runtime
check that the resulting program will run not just compile
and link.
> Strengthen the NVML check by adding a runtime check

- config/hwloc.m4
- hwloc/topology-levelzero.c
- tests/hwloc/ports/include/levelzero/level_zero/ze_api.h
When available, it gives the PCI locality without requiring Sysman.
If not, we fallback to Sysman as usual.
This is marked as a "standard" extension in the specs (as opposed to "experimental" extensions) hence it shouldn't break anytime soon.
> levelzero: use the core PCI prop extension if available

- NEWS
- hwloc/pci-common.c
- hwloc/topology.c
- include/private/private.h
Add a PCI locality quirk for the HPE Cray EX235a server used in the Frontier supercomputer. This requires to rework the old PCI locality quirk interface. By the way, we also add a debugging fake quirk.
> pci: rework locality quirks and add one for Cray/HPE EX235a

- tests/hwloc/hwloc_backends.c
Since 2.9, Linux discovery aborts if /sys isn't available. Usually it will fallback to the x86 backend... except on non-x86 platforms obviously where it would fallback to "noos" instead.
The hwloc_backends.c test verified that the "Backend" info attribute was the same in the XML-loaded topology and the original topology, but it did not handle the case where that info attribute did not exist at all, which is the case when only "noos" is used.
This is first reported by Simon South on https://issues.guix.gnu.org/61493
Thanks to Ludovic Courtes for forwarding to me.
> tests/backends.c: fix a failure when /sys isn't available on Linux on non-x86

- .gitignore
When configured with a non-native --host value, the libtool file will be prefixed by the host, which the current .gitignore misses.
> Update .gitignore to include cross-compile libtool artifacts

- utils/hwloc/misc.h
When using archivemount to load a topology, the directory hierarchy is traversed until a topology can be loaded. However, if an error occurs, it was silently ignored as the corresponding case reached the `break` and the `return 0` statements.
This commit adds the propagation of the error code (if it is not `0`).
> utils/archivemount: propagate error when visiting subdirs

- utils/hwloc/Makefile.am
- utils/lstopo/Makefile.am
- utils/netloc/infiniband/Makefile.am
Building with --target may add an unexpected prefix to the binary names. This commit uses the same mecanism to take this prefix in account.
Resolves #560
> Fix name scheme when building with --target

- doc/hwloc.doxy
- hwloc/topology-linux.c
Don't merge before candidate CXL patches (volatile region, etc) are merged Linux 6.3.
Things that don't work well yet in Linux:
* CXL PMEM DAX numa_node is always 0 ?
* CXL RAM DAX numa_node is always -1 ?
* How to specify this nodes' distance on the Qemu cmdline
Refs #554
> CXLDevice attributes in DAX and NUMA nodes

- utils/hwloc/hwloc-calc.c
- utils/hwloc/hwloc-distrib.c
- utils/hwloc/hwloc-info.c
- utils/hwloc/misc.h
- utils/lstopo/lstopo.c
This PR saves the current working directory and restores it after the topology has been loaded.
Solves #577 by ensuring the current directory does not change (at least not from a side effect of loading a topology).
> Archivemount restore working dir

- hwloc/topology-windows.c
- utils/lstopo/lstopo-draw.c
Avoids warning: passing argument 2 of 'GetComputerNameA' from incompatible pointer type [-Wincompatible-pointer-types]
> windows: Fix type of hostname_size parameter

- hwloc/shmem.c
- include/private/xml.h
This is mostly for fun, but there are two things that failed on a 128bit architecture (https://www.cl.cam.ac.uk/research/security/ctsrd/cheri/).
1. xml backend private data is stored in a opaque array to avoid propagating libxml stuff everywhere. this array wasn't big enough for 128bit pointers. fix it and make this is bit more portable (but still ugly).
2. the shmem header was only 64bit-aligned, hence the topology stored after it wasn't aligned either.
make check still fails on this architecture because of 'tag-write page fault' in the shmem. Basically we are supposed to share one process pointer with another process because addresses are tagged for security. There are workarounds (untag before writing to shmem and retag after adopting), but it would defeat the entire idea of shmem …
> Fixes for 128bit pointers on the CHERI architecture

- utils/hwloc/hwloc-annotate.c
- utils/hwloc/hwloc-bind.1in
- utils/hwloc/hwloc-calc.1in
- utils/hwloc/hwloc-calc.c
- utils/hwloc/hwloc-calc.h
- utils/hwloc/hwloc-info.1in
- utils/hwloc/hwloc-info.c
- utils/hwloc/hwloc.7in
- utils/hwloc/test-hwloc-calc.output
- utils/hwloc/test-hwloc-calc.sh.in
- utils/hwloc/test-hwloc-info.output
- utils/hwloc/test-hwloc-info.sh.in
- utils/lstopo/lstopo-no-graphics.1in
- utils/lstopo/lstopo-text.c
- utils/lstopo/lstopo.c
- utils/lstopo/lstopo.h
Generalize the existing OSDev[net] and PCI[vendor:device] with type[subtype]. This will notably be useful for selection different kinds of memory, e.g. NUMA[HBM].
This now works for locations given to tools (hwloc-bind/info/calc/annotate input objects) as well as options (hwloc-calc -N -I -H, lstopo --only, etc).
This replaces a lot of the old custom logic with a new "struct hwloc_calc_level" that describes a level (type, depth, attribute, subtype, etc) that may be used to filter input/output objects.
> utils: cleanup and improve location "filters"

- doc/hwloc.doxy
- hwloc/topology-linux.c
- utils/hwloc/hwloc-gather-topology.in
When running on NVIDIA Grace, force a single homogeneous cpukinds despite little frequency and capacity differences.
> NVIDIA Grace cpukinds

- README
- doc/hwloc.doxy
The GNU Make stuff is moved from the API example,
and CMake is added thanks to Florent Pruvost's example at https://gitlab.inria.fr/solverstack/distrib/-/tree/master/cmake/test/hwloc
Refs #565
> doxy: add a section about building with GNU Make and CMake

- NEWS
- doc/hwloc.doxy
- include/hwloc/deprecated.h
- include/hwloc/rename.h
Mark 1.x and obsolete and shouldn't be used.
Update examples of ABI/API/XML transitions.
Replace to 2.0 upgrade guide with 3.0.
By the way, remove some functions that were deprecated since 2.0.
> Update doxygen documentation to 3.0 API/ABI/XML changes

- NEWS
- contrib/completion/bash/hwloc
- utils/hwloc/hwloc-info.1in
- utils/hwloc/hwloc-info.c
- utils/hwloc/test-hwloc-info.output
- utils/hwloc/test-hwloc-info.sh.in
Add keywords to query levels, support and topo info just like other objects, depreate --objects/--topology/--support.
Add --get-attr to get a single info.
> hwloc-info improvements

- contrib/completion/bash/hwloc
https://github.com/open-mpi/hwloc/commit/e25888c9e4d1dcda8ff607f51207ca49cf89e15a introduced some syntax errors with missing open quotes on array members:
```
-bash: /opt/homebrew/etc/bash_completion.d/hwloc: line 210: syntax error near unexpected token `<'
-bash: /opt/homebrew/etc/bash_completion.d/hwloc: line 210: `		COMPREPLY=( "<integer>" "" )'
-bash: /opt/homebrew/etc/bash_completion.d/hwloc: line 211: syntax error near unexpected token `;;'
-bash: /opt/homebrew/etc/bash_completion.d/hwloc: line 211: `		;;'
```
and 
```
> shellcheck /opt/homebrew/etc/bash_completion.d/hwloc
In /opt/homebrew/etc/bash_completion.d/hwloc line 295:
COMPREPLY=( "hwloc" "list" taskset" )
^-- SC1009 (info): The mentioned syntax error was in this variable assignment.
^-- SC1073 (error): Couldn't parse this …
```
> fix: multiple syntax errors / missing quotes in hwloc bash completions

- hwloc/topology-linux.c
Fix https://github.com/open-mpi/hwloc/issues/676:
`HAVE_OPENAT` should not defined on old suse 9.
Change `hwloc_accessat` to inline version `hwloc_access` as it  preserves compiler parameter checking.
> fix#676 use hwloc_access instead of hwloc_accessat

- config/hwloc.m4
- doc/hwloc.doxy
- hwloc/topology-windows.c
Some future Windows release (TBD) will expose "Die" and "Module" information as well as NUMA nodes spanning mulitple processor groups. Bits are appearing in the onlie doc, we don't know all the details yet, and we don't have a way to test yet.
> Windows Die and Module (and NumaNodeEx) relationships

- config/hwloc.m4
- utils/lstopo/Makefile.am
Clang can be used in "MSVC mode" to build hwloc using autotools. That mode doesn't support -mwindows just like MSVC doesn't. -mwindows is the only difference between lstopo-win and lstopo, so just disable lstopo-win instead of building both identically.
Closes #631
> utils/lstopo: don't build lstopo-win with MSVC

- config/hwloc.m4
- doc/Makefile.am
- doc/hwloc.doxy
- hwloc/topology-levelzero.c
- hwloc/topology.c
- include/hwloc/levelzero.h
- include/hwloc/rename.h
- tests/hwloc/levelzero.c
- tests/hwloc/ports/Makefile.am
- tests/hwloc/ports/include/levelzero/level_zero/ze_api.h
- tests/hwloc/ports/include/levelzero/level_zero/zes_api.h
- only support implementations with zesDriverGetDeviceByUuidExp()
- the above means we may assume zesInit() is available and works
- remove the constructor that forces ZES_ENABLE_SYSMAN in the environment (FINALLY!!!)
- use different handles for ZE and ZES devices during discovery
- cleanup/update helpers and tests accordingly
Still needs to be tested on a machine with subdevices (PVC), but I don't have any such machine with a recent-enough L0 implementation.
> L0: switch to zesInit()

- hwloc/topology-levelzero.c
- include/hwloc/levelzero.h
- tests/hwloc/levelzero.c
- tests/hwloc/ports/include/levelzero/level_zero/ze_api.h
~~This goes on top of #594 which might be merged once a compute-runtime release brings a working zesInit(). This PR requires zesInit() to be more widely available, especially the last commit which completely remove the old setting of ZES_ENABLE_SYSMAN=1 in the env.~~
Now that we require zesInit(), just use ZES queries instead of switching from/to the Core API depending on ZES being available or not.
> levelzero: only use Sysman queries instead of similar Core API queries

- config/hwloc.m4
- hwloc/topology-rsmi.c
- tests/hwloc/ports/Makefile.am
- tests/hwloc/ports/include/rsmi/rocm_smi/rocm_smi.h
rsmi_dev_pci_id_get() returns the GPU "partition ID" inside the PCI BDF function, but this virtual function isn't actually exposed to the OS. See ROCm/rocm_smi_lib#208 for details.
When hwloc fails to find the corresponding PCI device, if the BDF function is > 0, get the RSMI partition ID, compare it with the BDF function, and try to get the PCI device with func = 0 instead.
Thanks to Edgar Leon for reporting the issue.
> rsmi: fix the PCI locality of partitioned devices

- tests/hwloc/hwloc_type_sscanf.c
E.g. with
HWLOC_SYNTHETIC="group:2 group:2 pu:2" ./tests/hwloc/hwloc_type_sscanf
The presence of the two group levels makes the check for level depth fail for the hwloc_obj_type_string case which does not expose attributes which allow to distinguish them.
> hwloc_type_sscanf: fix test when host has several levels with same type

- include/private/misc.h
This avoids use of the custom hwloc_flsl_manual() implementation if a recent GCC is in use.
It is not clear why the erroneous underscores, with which the macro does not seem to be defined anywhere, were introduced, as the commit introducing the line only references an SVN import. Older source releases however do not contain the change.
This was discovered as hwloc_flsl_manual() returns zero and as a result a division by zero exception with recent versions of GCC on certain CPU configurations, whereas the native functionality behaves correctly on both tested versions.
The manual implementation being defective is technically still an issue, however the logic under the __GNUC__ conditional is deemed to be preferable in any case.
Fixes: 3ac17a230d2a ("topo_cpuset_last")
Link: …
> misc: reactivate GNUC conditional

- config/hwloc.m4
- utils/lstopo/lstopo-ascii.c
Otherwise the output essentially always wraps around, making it unreadable.
> lstopo-ascii: Use a pager

- hwloc/distances.c
I did not see any other use of `HWLOC_DISTANCES_KIND_ALL` for filtering purposes, so I think only `hwloc_distances_get_by_name()` needed fixing here.
Fixes #730.
> Make hwloc_distances_get_by_name accept empty kinds
